[package]
name = "contract"
version = "0.0.1"
authors = ["Mario Reder <mario.reder@pm.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
contract-lib = { path = "../contract-lib" }
