name = "shitzu-hot-api"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-02-11"
node_compat = true

[vars]
NEAR_RPC_URL = "https://beta.rpc.mainnet.near.org"
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

[durable_objects]
bindings = [{ name = "INFO", class_name = "Info" }]

[[migrations]]
tag = "v1"
new_classes = ["Info"]
